_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_MEAN: [ 127.5, 127.5, 127.5 ]
  PIXEL_STD: [ 127.5, 127.5, 127.5 ]
  WEIGHTS: "./trained_ocr_cascade_large.pth"
  VIT:
    NAME: "dit_large_patch16"
    OUT_FEATURES: [ "layer7", "layer11", "layer15", "layer23" ]
    DROP_PATH: 0.2
  FPN:
    IN_FEATURES: [ "layer7", "layer11", "layer15", "layer23" ]
  ROI_HEADS:
    NAME: CascadeROIHeads
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
SOLVER:
  WARMUP_ITERS: 1000
  IMS_PER_BATCH: 16
  MAX_ITER: 60000
  CHECKPOINT_PERIOD: 2000
  BASE_LR: 0.0001
  STEPS: (40000, 53333)
  AMP:
    ENABLED: False

TEST:
  AUG:
    ENABLED: True
    FLIP: true
    MAX_SIZE: 4000
    MIN_SIZES:
    - 400
    - 500
    - 600
    - 700
    - 800
    - 900
    - 1000
    - 1100
    - 1200
  EVAL_PERIOD: 1000
  DETECTIONS_PER_IMAGE: 2500
  PRECISE_BN:
    ENABLED: False
    NUM_ITER: 200

OUTPUT_DIR: $AMLT_OUTPUT_DIR

INPUT:
  MAX_SIZE_TEST: 4000
  MAX_SIZE_TRAIN: 4000
  # MIN_SIZE_TEST: 800
  # MIN_SIZE_TEST: 800
