_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_MEAN: [ 127.5, 127.5, 127.5 ]
  PIXEL_STD: [ 127.5, 127.5, 127.5 ]
  WEIGHTS: "path/to/model"
  VIT:
    NAME: "dit_base_patch16"
  ANCHOR_GENERATOR:
    SIZES: [[4], [8], [16], [32], [64]]
    ASPECT_RATIOS: [[1.5, 3.5, 6.5]]
SOLVER:
  WARMUP_ITERS: 1000
  IMS_PER_BATCH: 4
  # MAX_ITER: 60000
  MAX_ITER: 400000
  CHECKPOINT_PERIOD: 1000
  BASE_LR: 0.0001
TEST:
  EVAL_PERIOD: 1000
  DETECTIONS_PER_IMAGE: 2000
OUTPUT_DIR: $$AMLT_OUTPUT_DIR

INPUT:
  # MAX_SIZE_TEST: 2500
  # MAX_SIZE_TRAIN: 2500
  MAX_SIZE_TEST: 768
  MAX_SIZE_TRAIN: 768
  MIN_SIZE_TEST: 768
