wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689033473.1518
    t:
      1:
      - 1
      - 5
      - 11
      - 43
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.10.6
      5: 0.15.5
      6: 4.30.2
      8:
      - 5
